# Generated by Django 3.2 on 2022-01-14 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy')], default='Action', max_length=10)),
                ('year', models.IntegerField(default=2000, verbose_name='Release Year')),
                ('source_url', models.CharField(default='#', max_length=256)),
                ('runtime', models.IntegerField(default=3600, verbose_name='Runtime')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('watchable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notflix.watchable')),
                ('thumbnail_url', models.CharField(default='notflix/media/thumbnails/placeholder_thumbnail_movie.jpg', max_length=256)),
                ('preview_url', models.CharField(default='notflix/media/previews/placeholder_preview_movie.mp4', max_length=256)),
            ],
            bases=('notflix.watchable',),
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('watchable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notflix.watchable')),
                ('season', models.PositiveIntegerField(default=1)),
                ('episode', models.PositiveIntegerField(default=1)),
                ('thumbnail_url', models.CharField(default='notflix/media/thumbnails/placeholder_thumbnail_tv.jpg', max_length=256)),
                ('preview_url', models.CharField(default='notflix/media/previews/placeholder_preview_tv.mp4', max_length=256)),
            ],
            bases=('notflix.watchable',),
        ),
        # migrations.CreateModel(
        #     name='Like',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('movies', models.ManyToManyField(default=None, to='notflix.Movie')),
        #         ('tvshows', models.ManyToManyField(default=None, to='notflix.TvShow')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DisLike',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('movies', models.ManyToManyField(default=None, to='notflix.Movie')),
        #         ('tvshows', models.ManyToManyField(default=None, to='notflix.TvShow')),
        #     ],
        # ),
    ]
