# Generated by Django 3.2 on 2021-04-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
